name: Kernel_CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 依赖环境
        run: |
          sudo apt install build-essential git curl wget bison flex zip bc cpio libssl-dev ccache
          mkdir ~/Clang
          cd ~/Clang
          wget https://github.com/ZyCromerZ/Clang/releases/download/20.0.0git-20250104-release/Clang-20.0.0git-20250104.tar.gz
          tar -zxvf Clang-20.0.0git-20250104.tar.gz
          cd ~/

      - name: 源码克隆
        run: |
          git clone https://github.com/localhosts-A/android_kernel_xiaomi_sm8250.git --depth=1

      - name: 内核编译
        run: |
          cd android_kernel_xiaomi_sm8250
          bash build.sh lmi ksu
          
